site_name: weccoframework/core
repo_url: https://github.com/weccoframework/core.git

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: amber
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: amber
    toggle:
      icon: material/brightness-4
      name: Switch to light mode    
  features:
  - content.code.copy
  - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/weccoframework/core


markdown_extensions:
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg  
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
